version: '3'
services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - '27017:27017'

  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database
    links:
      - database
    environment:
      - DOCKER=true

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - server
