version: '3'
services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - '27017:27017'

  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8080:8080'
    links:
      - database:mongo
    depends_on:
      - database

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - server